/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Auth": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "AuthClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "DatabaseMigrator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Internal": {
      "edgeSecret": string
      "ipSalt": string
      "type": "sst.sst.Linkable"
    }
    "Media": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "TurnstileSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.aws.Astro"
      "url": string
    }
  }
}

import "sst"
export {}